apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 737063749553.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest
        ports:
        - containerPort: 3000
      # Only include this if your EKS nodes don't have IAM role to access ECR
      # imagePullSecrets:
      # - name: ecr-secret

