apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80         # External port
      targetPort: 3000 # Container port in your Dockerfile

