name: CI/CD to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS credentials via OIDC (your IAM role)
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::737063749553:role/devops
        aws-region: ap-south-1

    # 3️⃣ Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t aws-assignment:latest .

    # 5️⃣ Tag and push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker tag aws-assignment:latest 737063749553.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest
        docker push 737063749553.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest

    # 6️⃣ Update kubeconfig to access EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name aws-assignment

    # 7️⃣ Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    # 8️⃣ Check service status
    - name: Get Service Info
      run: kubectl get svc
