name: CI/CD to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS credentials using secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3️⃣ Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t aws-assignment:latest .

    # 5️⃣ Tag and push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker tag aws-assignment:latest 737063749553.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest
        docker push 737063749553.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest

    # 6️⃣ Update kubeconfig for EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name aws-assignment

    # 7️⃣ Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    # 8️⃣ Get service info (optional)
    - name: Check service status
      run: kubectl get svc
